name: Manual Docker Build and Push with Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (default: latest)'
        required: false
        default: 'latest'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: cyprox
          password: ${{ secrets.CYPROX_DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image (v1)
        uses: docker/build-push-action@v1
        with:
          username: cyprox
          password: ${{ secrets.CYPROX_DOCKER_HUB_PASSWORD }}
          repository: cyprox/mcp-server
          tags: ${{ github.event.inputs.tag }}
          push: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: MCP Docker Image - ${{ github.event.inputs.tag }}
          body: |
            Docker image published to Docker Hub:
            `docker pull cyprox/mcp-server:${{ github.event.inputs.tag }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}